//
//  QuestionsDataBase.swift
//  iLoveYouApp
//
//  Created by Adm Aidyn on 10/30/21.
//

import Foundation

struct Questions {
    
    // MARK: - Questions by category
    
    let categories = ["Warm up", "Funny", "Sexy & Dirty", "Random"]
    
    let funny = ["The zombie apocalypse is coming, who are 3 people you want on your team?",
                 "Who was your childhood crush?",
                 "You have your own late night talk show, who do you invite as your first guest?",
                 "If you were famous, what would you be famous for?",
                 "If you had to eat one meal everyday for the rest of your life what would it be?",
                 "What is your guilty pleasure?",
                 "What did you get into the most trouble for with your parents as a kid?",
                 "If you were a potato, what way would you like to be cooked?",
                 "Have you ever been mistaken for someone famous?",
                 "What’s your spirit animal?",
                 "What’s the strangest gift you have ever received",
                 "What is your worst dating story?",
                 "If you could pick one superpower, what would  it be?",
                 "Your 3 most favorite desserts, go!",
                 "If you could take 3 people on an inhabited island with you, who’d they be?",
                 "Say two truths and one lie about you.", "What was the most hilarious incident at your job?",
                 "Have you ever pretended to have a skill or interest to please someone?",
                 "What was the most inappropriate thing you did in school?",
                 "Try to say a dad joke to each other.",
                 "What’s the best Wi-Fi name you’ve seen?",
                 "Toilet paper, over or under?",
                 "Where is the strangest place you’ve urinated or defecated?",
                 "In one sentence, how would you sum up the internet?",
                 "What mythical creature would improve the world if it existed?",
                 "What’s the weirdest thing you've seen in someone else's home?",
                 "If life was a video game, what cheat codes would you use?",
                 "What sport would be the funniest to add a mandatory amount of alcohol to?",
                 "What would be the coolest animal to scale up to the size of a horse?",
                 "What set of items could you buy that would make the cashier the most uncomfortable?",
                 "If all the States in the USA were represented by food, what food would each state be represented by?",
                 "If you were transported 400 years into the past with no clothes or anything else, how would you prove that you were from the future?",
                 "What is the sexiest and least sexy name?",
                 "Is a hotdog a sandwich? Why or why not?",
                 "Do you like pineapple on your pizza?",
                 "Finish the phrase: The roses are red, violets are blue…",
                 "Have you ever gone a day without wearing underwear?",
                 "Have you ever gone to the store and stolen something by accident?",
                 "If you were to be banned from your local library, what would be the reason?",
                 "What do you think is the worst thing that a person can put on their bio on a dating app?",
                 "Do mermaids have live babies or lay eggs?",
                 "What’s the most creative insult you can think of?",
                 "Have you ever been in a secret relationship?",
                 "Where would you like to time travel: back to the past or to the future?",
                 "What part of a kid’s movie completely scarred you?",
                 "Under the sheets, are you Iron Man, The Hulk, Thor, or Captain America?"
    ]
    
    
    
    let warmUp = ["Who was your childhood famous crush?",
                  "Would you rather be reincarnated as a cat or a dog?",
                  "Imagine you can instantly learn any language. Which would you choose?",
                  "Show each other your most-used emoji.",
                  "What superpower would you most want?",
                  "What’s your favorite drink?",
                  "Show each other your phone background and tell the story behind why you picked this image.",
                  "If you were professional at any sport, which would it be?",
                  "What is your most used phone app?",
                  "What is something we would not know about you just by looking?",
                  "What is your #1 recommendation in this city?",
                  "You can visit any fictional time or place. Which would you pick?",
                  "What is your favorite season?",
                  "Imagine you no longer have to work. How would you spend a Monday?",
                  "What was the worst job you ever had?",
                  "Which song could you listen to over and over again?",
                  "Who is the most famous person you have met?",
                  "What would it take to give up your smartphone for a month?",
                  "What food will you never eat?",
                  "Choose one famous person from history you want on your team during a zombie apocalypse.",
                  "Which movie made you laugh the most?",
                  "Would you rather have a pet sloth or a pet parrot?",
                  "Have you ever sung in the shower?",
                  "Imagine you could teleport anywhere. Where would you go right now?",
                  "Would you rather be an Avenger or a Power Ranger?",
                  "What is an easy way to do something nice for someone?",
                  "Would you rather live in a city or a town?",
                  "How do you like your potatoes?",
                  "Have you ever told someone Santa isn't real?",
                  "Wine and dine or Netflix and chill?",
                  "Coffee or tea?",
                  "Summer or snowy winter?",
                  "Comfy casual or fashionable and formal?",
                  "If you won the lottery, name 10 things you would spend your new funds on.",
                  "Owe money or owe a favor?",
                  "Rich and famous or rich and unknown?",
                  "Lose sleep or skip a meal?",
                  "Hang out with little kids or old folks?",
                  "Hot coffee or iced coffee?",
                  "How did you meet your best friend?",
                  "What’s your favorite meme or viral video?”",
                  "If you have an itch in your nose, in your butt, and on your eye, which one do you scratch first?”",
                  "What would your DJ name be?",
                  "Which celebrity do you wish was your BFF?",
                  "Multiple choice or essay"
    ]
    
//    let warmUp = ["Naruto", "Sasuke", "Kakashi", "Obito", "Madara"]
    
    let sexyDirty = ["What is the most reliable way for you to orgasm with a partner?",
                     "Would it turn you on to watch porn together?",
                     "What’s the sexual act you’ve never done, but want to try?",
                     "Do you prefer to be dominant or submissive?",
                     "What is your favorite place to touch yourself that’s not your genitals?",
                     "Do you prefer to give or receive",
                     "If you could sleep with any celebrity, who would it be?",
                     "Rough or romantic?",
                     "Do you like sexting?",
                     "If you could have sex anywhere in the world, where would it be?",
                     "When was the last time you had a dirty dream?",
                     "What’s the farthest you’ve gone on a first date?",
                     "Have you ever been caught going solo? By who?",
                     "Shaved or natural?",
                     "Have you ever had a friend with benefits?",
                     "Tight jeans or flirty skirt?",
                     "I come home from work stressed. How would you help me relax?",
                     "Have you ever done it in the backseat?",
                     "Have you ever taken nude pictures of yourself?",
                     "What kind of music do you like to play in the bedroom, if any?",
                     "What's your ideal date night?",
                     "What do you think of open relationships?",
                     "Has anyone accidentally seen you naked?",
                     "What is your opinion of hickeys?",
                     "Have you ever felt horny while texting on the phone?",
                     "Does being sneaky give you a thrill?",
                     "Tell each other a secret fantasy",
                     "Do you like coffee in the morning or tea?",
                     "Would you rather get a job promotion or sleep with your hot colleague?",
                     "Would you rather have nipples for toes or toes for nipples?",
                     "Would you have sex with a stranger or witn any of your friends?",
                     "Would you rather receive a sexy text message or sexy nudes?",
                     "Would you rather cheat on your partner and be caught or be cheated on and never be told?",
                     "Would you rather have really adventurous sex or romantic sex for the rest of your life?",
                     "Would you rather hook up with your doctor or your boss?",
                     "Would you rather let your spouse date your best friend or your arch enemy?",
                     "Would you rather stay virgin until you’re 40 or lose it with a sex worker?",
                     "What do you do when you’re horny in public?",
                     "How long should the act last?",
                     "In your opinion, what does it mean to be good in bed?",
                     "Would you ever make a sextape?",
                     "Would you ever do an onlyfans?",
                     "Do you like being spanked?",
                     "What should a partner do to impress you in bed?",
                     "What’s the first thing you noticed about my features?"
    ]
}
